name: flutter_default_text
version: 0.1.0
homepage: 'https://github.com/EdgarJan/flutter_default_text'
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0
flutter: